---

  - name: Set ntp configuration
    template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root
    become: yes
    become_method: sudo
    
  - name: Open firewalld udp/123
    firewalld:
      port: 123/udp 
      permanent: true
      state: enabled
      zone: "{{ ntp_fw_zone }}"
    become: yes
    become_method: sudo

  - name: Restart firewall
    systemd: 
      name: firewalld
      state: restarted 
      daemon_reload: yes
    become: yes
    become_method: sudo

  - name: Restart ntpd
    systemd: 
      name: ntpd 
      state: restarted 
      daemon_reload: yes
    become: yes
    become_method: sudo
