---

  - pause:
      prompt: "Make sure to copy repodata to {{ nginx_rootfolder }} before continuing"

  - name: Cleaning repo file
    file: path=/etc/yum.repos.d/{{ item }} state=absent
    with_items:
      - CentOS-CR.repo
      - CentOS-fasttrack.repo
      - CentOS-Sources.repo
      - CentOS-Base.repo
      - CentOS-Debuginfo.repo
      - CentOS-Media.repo
      - CentOS-Vault.repo
      - epel.repo
    become: yes
    become_method: sudo 

  - name: Copy local base repo file
    template: src=CentOS-Base-local.repo.j2 dest=/etc/yum.repos.d/CentOS-Base-local.repo owner=root group=root mode=0644
    become: yes
    become_method: sudo 

  - name: Copy local epel repo file
    template: src=epel-local.repo.j2 dest=/etc/yum.repos.d/epel-local.repo owner=root group=root mode=0644
    become: yes
    become_method: sudo 

  - name: Installation de nginx
    yum: name=nginx state=latest
    become: yes
    become_method: sudo

  - name: Copy nginx configuration file
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
    notify:
      - restart nginx
    become: yes
    become_method: sudo 

  - name: Ensure nginx is running and enabled
    service: name=nginx state=started enabled=yes
    become: yes
    become_method: sudo
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: Open firewalld tcp/80
    firewalld: 
      port: 80/tcp 
      permanent: true 
      state: enabled 
      zone: "{{ item }}"
    become: yes
    become_method: sudo
    with_items:
      - "{{ repo_fw_zone }}"

  - name: Restart firewalld service
    shell: systemctl restart firewalld
    become: yes
    become_method: sudo

  - name: Delete local base repo file
    file: 
      path: /etc/yum.repos.d/CentOS-Base-local.repo 
      state: absent
    become: yes
    become_method: sudo 

  - name: Delete local epel repo file
    file: 
      path: /etc/yum.repos.d/epel-local.repo 
      state: absent
    become: yes
    become_method: sudo 
