---

  - name: Looking for {{ inventory_hostname }}
    local_action:
      module: vmware_guest_facts
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ inventory_hostname }}"
      datacenter: "{{ datacenter }}"
    register: host_facts
    ignore_errors: yes

  - name: Hardening vmx
    shell: export LD_LIBRARY_PATH=/opt/shibboleth/lib64/:$LD_LIBRARY_PATH             
           && /usr/bin/powershell -NonInteractive {{ role_path }}/files/esxi_vmx_hardening.ps1 {{ vcenter_hostname }} {{ vcenter_username }} {{ vcenter_password }} {{ inventory_hostname }}
    delegate_to: localhost
    register: esxi_vmx_hardening
    failed_when: esxi_vmx_hardening.stderr
    when: host_facts.instance is defined
    tags:
      - vmx
