---

  - name: Looking for {{ inventory_hostname }}
    local_action:
      module: vmware_guest_facts
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ inventory_hostname }}"
      datacenter: "{{ datacenter }}"
    register: host_facts
    ignore_errors: yes

 
  - name: Poweroff VM {{ inventory_hostname }} 
    local_action:
      module: vmware_guest
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ inventory_hostname }}"
      state: poweredoff
      datacenter: "{{ datacenter }}"
    when: host_facts.instance is defined

  - name: Remove VM {{ inventory_hostname }} 
    local_action:
      module: vmware_guest
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ inventory_hostname }}"
      state: absent
      datacenter: "{{ datacenter }}"
    when: host_facts.instance is defined
