---

## Already exists ?
  - name: Looking for {{ template }} in cluster {{ zone }}
    local_action:
      module: vmware_guest_facts
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ template }}-{{ zone | regex_replace(' ') }}"
      datacenter: "{{ datacenter }}"
    register: template_facts
    ignore_errors: yes
 
  - name: Import template "{{ template }}-{{ zone | regex_replace(' ') }}" to vcenter
    shell: export LD_LIBRARY_PATH=/opt/shibboleth/lib64/:$LD_LIBRARY_PATH             
           && /usr/bin/powershell -NonInteractive {{ role_path }}/files/esxi_import_ova.ps1 
                {{ vcenter_hostname }} 
                {{ vcenter_username }} 
                {{ vcenter_password }}
                {{ template_dir }}
                {{ template }}
                {{ compute }}
                """'{{ datastore }}'"""
                """'{{ zone }}'"""
    delegate_to: localhost
    register: import
    failed_when: import.stderr
    when: template_facts.instance is not defined
    tags:
      - import-ova
